config/routes.rb
Rails.application.routes.draw do
  get 'super_users/dashboard'

  get 'clients/dashboard'
  get "clients/client_info" => 'clients#trans_info', :as => :trans_info
  
  resources :freight_missions

  resources :trips

  resources :clients do
  end

  get 'transporters/dashboard'
  get "transporters/client_info" => 'transporters#client_info', :as => :client_info


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'welcome/index'

  # root 'welcome#index'
  devise_scope :user do
    root to: "devise/sessions#new"
  end
end

app/models/trip.rb
class Trip < ApplicationRecord
  
  belongs_to :user

  # validates :departure_city, presence: true
  # validates :arrival_city, presence: true
  # validates :type_of_goods, presence: true
  # validates :dimensions, presence: true
  # validates :pick_up_date, presence: true
  # validates :pick_up_time_min, presence: true
  # validates :pick_up_time_max, presence: true
  # validates :delivery_date, presence: true
  # validates :delivery_time_min, presence: true
  # validates :delivery_time_max, presence: true
  # validates :phone, presence: true
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  def index
    @trips = current_user.trips
  end

  def show
  end

  def new
    @trip = Trip.new
  end

  def edit
  end

  def create
    @trip = current_user.trips.new(trip_params)
    respond_to do |format|
      if @trip.save
        # SendSmsWorker.perform_async
        if current_user.super_user?
          format.html { redirect_to super_users_dashboard_path, notice: 'Trip was successfully created.' }
        else
          format.html { redirect_to transporters_dashboard_path, notice: 'Trip was successfully created.' }
        end
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @trip.update(trip_params)
        if current_user.super_user?
          format.html { redirect_to super_users_dashboard_path, notice: 'Trip was successfully updated.' }
        else
          format.html { redirect_to transporters_dashboard_path, notice: 'Trip was successfully updated.' }
        end
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @trip.destroy
    respond_to do |format|
      if current_user.super_user?
        format.html { redirect_to super_users_dashboard_path, notice: 'Trip was successfully destroyed.' }
      else
        format.html { redirect_to transporters_dashboard_path, notice: 'Trip was successfully destroyed.' }
      end
    end
  end

  private
    def set_trip
      @trip = Trip.find(params[:id])
    end

    def trip_params
      params.require(:trip).permit(:weight, :type_of_truck, :contact, :arrival_hours, :depart_hours, :departure_city, :arrival_city, :pick_up_date, :delivery_date)
    end
end

app/helpers/trips_helper.rb
module TripsHelper
  def is_trip_new?
    true if params[:controller] == "trips" and (params[:action] == "new" or params[:action] == "create")
  end
end

app/views/trips/_form.html.haml
%section.career.career-desktop
  .container-fluid
    .row
      = render "shared/side_panel"
      .col-lg-10.col-md-10.col-sm-12.col-xs-12.right-content{:style => "background: #f7f7f7;margin: 0;"}
        .row
          .col-lg-2.col-md-2.col-sm-2.col-xs-2.hidden-lg.hidden-md
            %h2
              - if current_user.super_user?
                = link_to '<i class="fa fa-arrow-left mango" aria-hidden="true" style="color: #000;"></i>'.html_safe, super_users_dashboard_path
              - else
                = link_to '<i class="fa fa-arrow-left mango" aria-hidden="true" style="color: #000;"></i>'.html_safe, transporters_dashboard_path  
        .row
          .col-lg-12.col-md-12.col-sm-12.col-xs-12
            %p.form-p.txtNouvel Nouveau trajet
        .row-fluid
          .col-lg-12.col-md-12.col-sm-12.col-xs-12
            %div
              = form_for @trip, validate: true, html: {class: 'login mission'} do |f|
                .text-black.m-b-2perc
                  .row
                    .col-lg-5.col-md-5.col-sm-12.col-xs-12.text-left.m-b-8prc
                      = f.select :departure_city, [['Tunis', 'Tunis'], ['Sfax', 'Sfax'], ['Sousse', 'Sousse']], {prompt: 'Ville de départ *'}, {class: "brd-btm border-bottom form-control drpNoStyle"}
                      %span.depart-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide  
                    .col-lg-1.col-md-1.col-sm-12.col-xs-12.text-center.box-imgonmob
                      = image_tag "up.png", class: "img-box", alt: "", tabindex: "-1"
                    .col-lg-6.col-md-6.col-sm-12.col-xs-12.m-b-8prc.text-left
                      .input-group.add-on
                        = f.text_field :pick_up_date, class: "input-search datepicker-mission", placeholder: "Date de départ *", readonly: true
                        .input-group-btn
                          %button.btn.btn-default{:tabindex => "-1", :type => "button"}
                            %i.fa.fa-calendar-check-o{"aria-hidden" => "true"}
                      %span.pick_date-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide
                %div.m-b-2perc
                  .row
                    .col-lg-5.col-md-5.col-sm-12.col-xs-12.m-b-8prc.text-left.hidden-xs
                      = f.select :arrival_city, [['Tunis', 'Tunis'], ['Sfax', 'Sfax'], ['Sousse', 'Sousse']], {prompt: 'Ville d’arrivée *'}, {class: "brd-btm border-bottom form-control drpNoStyle"}
                      %span.city-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide
                    .col-lg-1.col-md-1.col-sm-12.col-xs-12.text-center
                    .col-lg-6.col-md-6.col-sm-12.col-xs-12.text-left
                      .row
                        .col-lg-6.col-md-6.col-sm-12.col-xs-12.m-b-8prc
                          .input-group.add-on
                            = f.text_field :depart_hours, class: "input-search timepicker-mission", placeholder: "Heure *", validate: true, readonly: true
                            .input-group-btn
                              %button.btn.btn-default{:tabindex => "-1", :type => "button"}
                                %i.fa.fa-clock-o{"aria-hidden" => "true"}
                          %span.pick_time_min-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide
                .text-black.m-b-2perc
                  .row
                    .col-lg-5.col-md-5.col-sm-12.col-xs-12.text-left.hidden-xs
                      = f.text_field :type_of_truck, placeholder: "Type de camion *"  ,class: "brd-btm border-bottom goods"
                      %span.goods-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide
                    .col-lg-1.col-md-1.col-sm-12.col-xs-12.box-imgonmob
                      = image_tag "down.png", class: "img-box", alt: "", tabindex: "-1"
                    .col-lg-6.col-md-6.col-sm-12.col-xs-12.m-b-8prc.text-left
                      .input-group.add-on
                        = f.text_field(:delivery_date, validate: true, class: "input-search datepicker-mission", placeholder: "Date d’arrivée *", readonly: true)
                        .input-group-btn
                          %button.btn.btn-default{:tabindex => "-1", :type => "button"}
                            %i.fa.fa-calendar-check-o{"aria-hidden" => "true"}
                      %span.delivery_date-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide
                %div.m-b-2perc
                  .row
                    .col-lg-5.col-md-5.col-sm-12.col-xs-12.m-b-8prc.text-left.hidden-xs
                      = f.text_field :weight, placeholder: "Charge utile *"  ,class: "brd-btm border-bottom dimensions"
                      %span.dimension-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide
                    .col-lg-1.col-md-1.col-sm-12.col-xs-12.text-center
                    .col-lg-6.col-md-6.col-sm-12.col-xs-12
                      .row
                        .col-lg-6.col-md-6.col-sm-12.col-xs-12.m-b-8prc.text-left
                          .input-group.add-on
                            = f.text_field :arrival_hours, validate: true, class: "input-search timepicker-mission", placeholder: "Heure *", readonly: true
                            .input-group-btn
                              %button.btn.btn-default{:tabindex => "-1", :type => "button"}
                                %i.fa.fa-clock-o{"aria-hidden" => "true"}
                          %span.delivery_time_min-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide
                %div
                  .row
                    .col-lg-5.col-md-5.col-sm-12.col-xs-12.m-b-8prc.text-left
                      = f.text_field :contact, placeholder: "Numéro à contacter *" , class: "brd-btm border-bottom"
                      %span.phone-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide
                    .col-lg-1.col-md-1.col-sm-12.col-xs-12.text-center
                %label.message{:for => "\#{instance.send(:tag_id)}"}
                .form-group
                  .row
                    .col-lg-12
                      %input#submitbtntrip.btn-publisher.text-white.btn.btn-sm.btn-submit{:type => "submit", :value => "Poster"}/

app/views/trips/_trips.html.haml
- if current_user.super_user?
  - @trips = trips
- if @trips.present?
  - @trips.each do |ftrips|
    .row
      .col-lg-12.col-md-12.col-sm-12.col-xs-12
        .panel.panel-default
          .panel-body.dashboard-panels
            .row
              .col-lg-6.col-md-6.col-sm-6.col-xs-6
                %section.panel-left
                  - if (actor.eql? "Client")
                    %h5
                      %b= ftrips.user.company
                  %h5.txt-tunis.side-para
                    %strong= "#{ftrips.departure_city} -> #{ftrips.arrival_city}"
                  %p.text-gray.m-b-3.side-para= ftrips.type_of_truck
                  %p.text-gray.m-b-3.side-para= ftrips.weight
                  %p.text-gray.hidden-xs.side-para.mission-details
              .col-lg-6.col-md-6.col-sm-6.col-xs-6{:style => "border-left: 1px solid #ccc;"}
                %section.panel-right
                  .row
                    .col-lg-2.col-sm-2.col-xs-3.counter-Sec
                      = image_tag "up.png", class: "img-box img-box-db", alt: ""
                    .col-lg-10.col-sm-10.col-xs-9
                      %p.txtmonth
                        %span= date_format(ftrips.pick_up_date)
                      %p.txtTime
                        %strong= "#{ftrips.arrival_hours}"
                  .row
                    .col-lg-2.col-sm-2.col-xs-3
                      = image_tag "down.png", class: "img-box img-box-db", alt: ""
                    .col-lg-10.col-sm-10.col-xs-9
                      %p.txtmonth
                        %span= date_format(ftrips.delivery_date)
                      %p.txtTime
                        %strong= "#{ftrips.depart_hours}"
                  %br/      
                  .row.hidden-xs
                    .col-lg-12.col-sm-12
                      - if (actor.eql? "Client")
                        = link_to 'Voir numéro', trans_info_path(ftrips: ftrips.id),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#transinfoModal', class: "btn btn-color btn-modal btn-block"}
                      -else
                        %button.btn-primary.btn-block.btn-en.btn-non-pointer{:type => ""} En cours    
            .row.hidden-lg.hidden-md.hidden-sm
              .col-xs-12
                %p.text-gray.side-para.mission-details.mission-details-tab
            .row.hidden-lg.hidden-md.hidden-sm
              .col-lg-12.col-sm-12.col-enbtn
                %br/
                -# if (params["controller"].eql? "transporters") || (actor.eql? "Client" || current_user.super_user?)
                - if (actor.eql? "Client")
                  = link_to 'Voir numéro', trans_info_path(ftrips: ftrips.id),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#transinfoModal', class: "btn btn-color btn-modal btn-block"}
                - else  
                  %button.btn-primary.btn-block.btn-en.btn-non-pointer{:type => ""} En cours          
- else
  Pas de mission créée pour l'instant.

app/views/trips/edit.html.erb
<h1>Editing trips</h1>

<%= render 'form', trips: @trips %>

<%= link_to 'Show', @trips %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.haml
= render 'shared/header'
%section.career.dashboard
  .container-fluid
    .row
      = render "shared/side_panel"
      .col-lg-10.col-md-10.col-sm-10.col-xs-10.right-content{:style => "background: #f7f7f7;margin: 0;"}
        .row
          .col-lg-12.col-md-12.col-sm-12.col-xs-12
            %h4
              %span
                %b Historique des trips
            %hr{:style => "border-top: 1px solid #cecbcb;margin-top: 0px;"}/
        = render "trips"

app/views/trips/new.html.haml
= render 'shared/header'
= render 'form', trip: @trip

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Departure city:</strong>
  <%= @trip.departure_city %>
</p>

<p>
  <strong>Arrival city:</strong>
  <%= @trip.arrival_city %>
</p>

<p>
  <strong>Type of goods:</strong>
  <%= @trip.type_of_goods %>
</p>

<p>
  <strong>Dimensions:</strong>
  <%= @trip.dimensions %>
</p>

<p>
  <strong>Pick up date:</strong>
  <%= @trip.pick_up_date %>
</p>

<p>
  <strong>Pick up time:</strong>
  <%= @trip.pick_up_time %>
</p>

<p>
  <strong>Delivery date:</strong>
  <%= @trip.delivery_date %>
</p>

<p>
  <strong>Delivery time:</strong>
  <%= @trip.delivery_time %>
</p>

<p>
  <strong>Specific details:</strong>
  <%= @trip.specific_details %>
</p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>