config/routes.rb
Rails.application.routes.draw do
  get 'super_users/dashboard'

  get 'clients/dashboard'
  get "clients/client_info" => 'clients#trans_info', :as => :trans_info
  
  resources :freight_missions

  resources :trips

  resources :clients do
  end

  get 'transporters/dashboard'
  get "transporters/client_info" => 'transporters#client_info', :as => :client_info


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'welcome/index'

  # root 'welcome#index'
  devise_scope :user do
    root to: "devise/sessions#new"
  end
end

app/views/shared/_header.html.erb
<nav class="navbar navbar-default kamioun-navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed hide" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
        <%= image_tag "logo-kamioun-min.png", class: "logo-img", alt: ""  %>
        <span class="txtKamiounLi text-white txtformob">Kamioun</span>
      </a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Se déconnecter", destroy_user_session_path  %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_side_panel.html.haml
.col-lg-2.col-md-2.col-sm-2.col-xs-2.bg-white.side-nav.hidden-xs.hidden-sm
  - if is_mission_new? || is_trip_new?
    %h4
      %span
        %i.fa.fa-arrow-left{"aria-hidden" => "true"}
      %b.side-panel-text
        - if current_user.super_user?
          = link_to "Historique", super_users_dashboard_path
        - elsif current_user.transporter?
          = link_to "Historique", transporters_dashboard_path
        -else
          = link_to "Historique", clients_dashboard_path
  - elsif current_user.transporter?
    %button.btn.btn-block.btn-ajouter{:type => ""}= link_to "Ajouter une mission", new_trip_path
  - else
    %button.btn.btn-block.btn-ajouter{:type => ""}= link_to "Ajouter une mission", new_freight_mission_path