config/routes.rb
Rails.application.routes.draw do
  get 'super_users/dashboard'

  get 'clients/dashboard'
  get "clients/client_info" => 'clients#trans_info', :as => :trans_info
  
  resources :freight_missions

  resources :trips

  resources :clients do
  end

  get 'transporters/dashboard'
  get "transporters/client_info" => 'transporters#client_info', :as => :client_info


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'welcome/index'

  # root 'welcome#index'
  devise_scope :user do
    root to: "devise/sessions#new"
  end
end

app/models/freight_mission.rb
class FreightMission < ApplicationRecord

  # belongs_to :client
  # belongs_to :super_user
  belongs_to :user

  validates :departure_city, presence: true
  validates :arrival_city, presence: true
  validates :type_of_goods, presence: true
  validates :dimensions, presence: true
  validates :pick_up_date, presence: true
  validates :pick_up_time_min, presence: true
  validates :pick_up_time_max, presence: true
  validates :delivery_date, presence: true
  validates :delivery_time_min, presence: true
  validates :delivery_time_max, presence: true
  validates :phone, presence: true

end

app/controllers/freight_missions_controller.rb
class FreightMissionsController < ApplicationController
  before_action :set_freight_mission, only: [:show, :edit, :update, :destroy]

  def index
    @freight_missions = current_user.freight_missions
  end

  def show
  end

  def new
    @freight_mission = FreightMission.new
  end

  def edit
  end

  def create
    @freight_mission = current_user.freight_missions.new(freight_mission_params)
    respond_to do |format|
      if @freight_mission.save
        SendSmsWorker.perform_async
        if current_user.super_user?
          format.html { redirect_to super_users_dashboard_path, notice: 'Freight mission was successfully created.' }
        else
          format.html { redirect_to clients_dashboard_path, notice: 'Freight mission was successfully created.' }
        end
      else
        format.html { render :new }
        format.json { render json: @freight_mission.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @freight_mission.update(freight_mission_params)
        if current_user.super_user?
          format.html { redirect_to super_users_dashboard_path, notice: 'Freight mission was successfully updated.' }
        else
          format.html { redirect_to clients_dashboard_path, notice: 'Freight mission was successfully updated.' }
        end
      else
        format.html { render :edit }
        format.json { render json: @freight_mission.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @freight_mission.destroy
    respond_to do |format|
      if current_user.super_user?
        format.html { redirect_to super_users_dashboard_path, notice: 'Freight mission was successfully destroyed.' }
      else
        format.html { redirect_to clients_dashboard_path, notice: 'Freight mission was successfully destroyed.' }
      end
    end
  end

  private
    def set_freight_mission
      @freight_mission = FreightMission.find(params[:id])
    end

    def freight_mission_params
      params.require(:freight_mission).permit(:departure_city, :arrival_city, :type_of_goods, :dimensions, :pick_up_date, :pick_up_time_min, :pick_up_time_max, :delivery_date, :delivery_time_min, :delivery_time_max, :specific_details, :phone)
    end
end

app/helpers/freight_missions_helper.rb
module FreightMissionsHelper

  def is_mission_new?
    true if params[:controller] == "freight_missions" and (params[:action] == "new" or params[:action] == "create")
  end
  
end

app/views/freight_missions/_form.html.haml
%section.career.career-desktop
  .container-fluid
    .row
      = render "shared/side_panel"
      .col-lg-10.col-md-10.col-sm-12.col-xs-12.right-content{:style => "background: #f7f7f7;margin: 0;"}
        .row
          .col-lg-2.col-md-2.col-sm-2.col-xs-2.hidden-lg.hidden-md
            %h2
              - if current_user.super_user?
                = link_to '<i class="fa fa-arrow-left mango" aria-hidden="true" style="color: #000;"></i>'.html_safe, super_users_dashboard_path
              - else
                = link_to '<i class="fa fa-arrow-left mango" aria-hidden="true" style="color: #000;"></i>'.html_safe, clients_dashboard_path  
        .row
          .col-lg-12.col-md-12.col-sm-12.col-xs-12
            %p.form-p.txtNouvel Nouvelle mission
        .row-fluid
          .col-lg-12.col-md-12.col-sm-12.col-xs-12
            %div
              = form_for @freight_mission, validate: true, html: {class: 'login mission'} do |f|
                .text-black.m-b-2perc
                  .row
                    .col-lg-5.col-md-5.col-sm-12.col-xs-12.text-left.m-b-8prc
                      = f.select :departure_city, [['Tunis', 'Tunis'], ['Sfax', 'Sfax'], ['Sousse', 'Sousse']], {prompt: 'Ville de départ *'}, {class: "brd-btm border-bottom form-control drpNoStyle"}
                      %span.depart-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide
                    .col-lg-5.col-md-5.col-sm-12.col-xs-12.text-left.m-b-8prc.hidden-lg.hidden-md.hidden-sm
                      = f.select :arrival_city, [['Tunis', 'Tunis'], ['Sfax', 'Sfax'], ['Sousse', 'Sousse']], {prompt: 'Ville d’arrivée *'}, {class: "brd-btm drpNoStyle border-bottom form-control arrival_city"}
                      %span.city-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide  
                    .col-lg-5.col-md-5.col-sm-12.col-xs-12.text-left.m-b-8prc.hidden-lg.hidden-md.hidden-sm
                      = f.text_field :type_of_goods, placeholder: "Type de marchandises *"  ,class: "brd-btm border-bottom goods"
                      %span.goods-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide
                    .col-lg-5.col-md-5.col-sm-12.col-xs-12.text-left.m-b-8prc.hidden-lg.hidden-md.hidden-sm
                      = f.text_field :dimensions, placeholder: "Taille/Poids/Nombre de palettes *"  ,class: "brd-btm border-bottom dimensions"
                      %span.dimension-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide    
                    .col-lg-1.col-md-1.col-sm-12.col-xs-12.text-center.box-imgonmob
                      = image_tag "up.png", class: "img-box", alt: "", tabindex: "-1"
                    .col-lg-6.col-md-6.col-sm-12.col-xs-12.m-b-8prc.text-left
                      .input-group.add-on
                        = f.text_field :pick_up_date, class: "input-search datepicker-mission", placeholder: "Date de collecte *", readonly: true
                        .input-group-btn
                          %button.btn.btn-default{:tabindex => "-1", :type => "button"}
                            %i.fa.fa-calendar-check-o{"aria-hidden" => "true"}
                      %span.pick_date-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide
                %div.m-b-2perc
                  .row
                    .col-lg-5.col-md-5.col-sm-12.col-xs-12.m-b-8prc.text-left.hidden-xs
                      = f.select :arrival_city, [['Tunis', 'Tunis'], ['Sfax', 'Sfax'], ['Sousse', 'Sousse']], {prompt: 'Ville d’arrivée *'}, {class: "brd-btm drpNoStyle border-bottom form-control arrival_city"}
                      %span.city-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide
                    .col-lg-1.col-md-1.col-sm-12.col-xs-12.text-center
                    .col-lg-6.col-md-6.col-sm-12.col-xs-12.text-left
                      .row
                        .col-lg-6.col-md-6.col-sm-12.col-xs-12.m-b-8prc
                          .input-group.add-on
                            = f.text_field :pick_up_time_min, class: "input-search timepicker-mission", placeholder: "Heure min. *", validate: true, readonly: true
                            .input-group-btn
                              %button.btn.btn-default{:tabindex => "-1", :type => "button"}
                                %i.fa.fa-clock-o{"aria-hidden" => "true"}
                          %span.pick_time_min-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide
                        .col-lg-6.col-md-6.col-sm-12.col-xs-12.text-left
                          .input-group.add-on
                            = f.text_field :pick_up_time_max, validate: true, class: "input-search timepicker-mission", placeholder: "Heure max. *", readonly: true
                            .input-group-btn
                              %button.btn.btn-default{:tabindex => "-1", :type => "button"}
                                %i.fa.fa-clock-o{"aria-hidden" => "true"}
                          %span.pick_time_max-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide
                .text-black.m-b-2perc
                  .row
                    .col-lg-5.col-md-5.col-sm-12.col-xs-12.text-left.hidden-xs
                      = f.text_field :type_of_goods, placeholder: "Type de marchandises *"  ,class: "brd-btm border-bottom goods"
                      %span.goods-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide
                    .col-lg-1.col-md-1.col-sm-12.col-xs-12.box-imgonmob
                      = image_tag "down.png", class: "img-box", alt: "", tabindex: "-1"
                    .col-lg-6.col-md-6.col-sm-12.col-xs-12.m-b-8prc.text-left
                      .input-group.add-on
                        = f.text_field(:delivery_date, validate: true, class: "input-search datepicker-mission", placeholder: "Date de livraison *", readonly: true)
                        .input-group-btn
                          %button.btn.btn-default{:tabindex => "-1", :type => "button"}
                            %i.fa.fa-calendar-check-o{"aria-hidden" => "true"}
                      %span.delivery_date-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide
                %div.m-b-2perc
                  .row
                    .col-lg-5.col-md-5.col-sm-12.col-xs-12.m-b-8prc.text-left.hidden-xs
                      = f.text_field :dimensions, placeholder: "Taille/Poids/Nombre de palettes *"  ,class: "brd-btm border-bottom dimensions"
                      %span.dimension-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide
                    .col-lg-1.col-md-1.col-sm-12.col-xs-12.text-center
                    .col-lg-6.col-md-6.col-sm-12.col-xs-12
                      .row
                        .col-lg-6.col-md-6.col-sm-12.col-xs-12.m-b-8prc.text-left
                          .input-group.add-on
                            = f.text_field :delivery_time_min, validate: true, class: "input-search timepicker-mission", placeholder: "Heure min. *", readonly: true
                            .input-group-btn
                              %button.btn.btn-default{:tabindex => "-1", :type => "button"}
                                %i.fa.fa-clock-o{"aria-hidden" => "true"}
                          %span.delivery_time_min-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide
                        .col-lg-6.col-md-6.col-sm-12.col-xs-12.text-left.m-b-8prc
                          .input-group.add-on
                            = f.text_field :delivery_time_max, validate: true, class: "delivery_max input-search timepicker-mission", placeholder: "Heure max. *", readonly: true
                            .input-group-btn
                              %button.btn.btn-default{:tabindex => "-1", :type => "button"}
                                %i.fa.fa-clock-o{"aria-hidden" => "true"}
                          %span.delivery_time_max-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide
                %div
                  .row
                    .col-lg-5.col-md-5.col-sm-12.col-xs-12.m-b-8prc.text-left
                      = f.text_field :phone, placeholder: "Numéro à contacter *" , class: "brd-btm border-bottom"
                      %span.phone-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide
                    .col-lg-1.col-md-1.col-sm-12.col-xs-12.text-center
                    .col-lg-6.col-md-6.col-sm-12.col-xs-12.m-b-8prc.text-left
                      = f.text_field :specific_details, placeholder: "Type de véhicule demandé/Autres détails"  ,class: "brd-btm border-bottom"
                      %span.details-error.hide{:style => "font-size:10px;color:red;text-align: left;"} *cela ne peut pas être vide
                %label.message{:for => "\#{instance.send(:tag_id)}"}
                .form-group
                  .row
                    .col-lg-12
                      %input#submitbtn.btn-publisher.text-white.btn.btn-sm.btn-submit{:type => "submit", :value => "Poster"}/

app/views/freight_missions/_missions.html.haml
- if current_user.super_user?
  - @freight_missions = missions
- if @freight_missions.present?
  - @freight_missions.each do |fmission|
    .row
      .col-lg-12.col-md-12.col-sm-12.col-xs-12
        .panel.panel-default
          .panel-body.dashboard-panels
            .row
              .col-lg-6.col-md-6.col-sm-6.col-xs-6
                %section.panel-left
                  - if (params["controller"].eql? "transporters") || (actor.eql? "Transporter")
                    %h5
                      %b= fmission.user.company
                  %h5.txt-tunis.side-para
                    %strong= "#{fmission.departure_city} -> #{fmission.arrival_city}"
                  %p.text-gray.m-b-3.side-para= fmission.type_of_goods
                  %p.text-gray.m-b-3.side-para= fmission.dimensions
                  %p.text-gray.hidden-xs.side-para.mission-details
                    %i= fmission.specific_details
              .col-lg-6.col-md-6.col-sm-6.col-xs-6{:style => "border-left: 1px solid #ccc;"}
                %section.panel-right
                  .row
                    .col-lg-2.col-sm-2.col-xs-3.counter-Sec
                      = image_tag "up.png", class: "img-box img-box-db", alt: ""
                    .col-lg-10.col-sm-10.col-xs-9
                      %p.txtmonth
                        %span= date_format(fmission.pick_up_date)
                      %p.txtTime
                        %strong= "#{fmission.pick_up_time_max}-#{fmission.pick_up_time_min}"
                  .row
                    .col-lg-2.col-sm-2.col-xs-3
                      = image_tag "down.png", class: "img-box img-box-db", alt: ""
                    .col-lg-10.col-sm-10.col-xs-9
                      %p.txtmonth
                        %span= date_format(fmission.delivery_date)
                      %p.txtTime
                        %strong= "#{fmission.delivery_time_max}-#{fmission.delivery_time_min}"
                  %br/      
                  .row.hidden-xs
                    .col-lg-12.col-sm-12
                      - if (params["controller"].eql? "transporters") || (actor.eql? "Transporter")
                        = link_to 'Voir numéro', client_info_path(fmission: fmission.id),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#clientinfoModal', class: "btn btn-color btn-modal btn-block"}
                      -else
                        %button.btn-primary.btn-block.btn-en.btn-non-pointer{:type => ""} En cours    
            .row.hidden-lg.hidden-md.hidden-sm
              .col-xs-12
                %p.text-gray.side-para.mission-details.mission-details-tab
                  %i= fmission.specific_details
            .row.hidden-lg.hidden-md.hidden-sm
              .col-lg-12.col-sm-12.col-enbtn
                %br/
                - if (params["controller"].eql? "transporters") || (actor.eql? "Transporter")
                  = link_to 'Voir numéro', client_info_path(fmission: fmission.id),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#clientinfoModal', class: "btn btn-color btn-modal btn-block"}
                - else  
                  %button.btn-primary.btn-block.btn-en.btn-non-pointer{:type => ""} En cours          
- else
  Pas de mission créée pour l'instant.

app/views/freight_missions/edit.html.erb
<h1>Editing Freight Mission</h1>

<%= render 'form', freight_mission: @freight_mission %>

<%= link_to 'Show', @freight_mission %> |
<%= link_to 'Back', freight_missions_path %>

app/views/freight_missions/index.html.haml
= render 'shared/header'
%section.career.dashboard
  .container-fluid
    .row
      = render "shared/side_panel"
      .col-lg-10.col-md-10.col-sm-10.col-xs-10.right-content{:style => "background: #f7f7f7;margin: 0;"}
        .row
          .col-lg-12.col-md-12.col-sm-12.col-xs-12
            %h4
              %span
                %b Historique des missions
            %hr{:style => "border-top: 1px solid #cecbcb;margin-top: 0px;"}/
        = render "missions"

app/views/freight_missions/new.html.haml
= render 'shared/header'
= render 'form', freight_mission: @freight_mission

app/views/freight_missions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Departure city:</strong>
  <%= @freight_mission.departure_city %>
</p>

<p>
  <strong>Arrival city:</strong>
  <%= @freight_mission.arrival_city %>
</p>

<p>
  <strong>Type of goods:</strong>
  <%= @freight_mission.type_of_goods %>
</p>

<p>
  <strong>Dimensions:</strong>
  <%= @freight_mission.dimensions %>
</p>

<p>
  <strong>Pick up date:</strong>
  <%= @freight_mission.pick_up_date %>
</p>

<p>
  <strong>Pick up time:</strong>
  <%= @freight_mission.pick_up_time %>
</p>

<p>
  <strong>Delivery date:</strong>
  <%= @freight_mission.delivery_date %>
</p>

<p>
  <strong>Delivery time:</strong>
  <%= @freight_mission.delivery_time %>
</p>

<p>
  <strong>Specific details:</strong>
  <%= @freight_mission.specific_details %>
</p>

<%= link_to 'Edit', edit_freight_mission_path(@freight_mission) %> |
<%= link_to 'Back', freight_missions_path %>